### PR TITLE
Fix python_2_unicode_compatible import error (closes #26)

### LINKED ISSUE #26: Django 3 doesn't support python_2_unicode_compatible any more
This library produces an error on Django 3:

```
Traceback (most recent call last):
  File "./manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/.virtualenvs/project/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/.virtualenvs/project/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/user/.virtualenvs/project/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/user/.virtualenvs/project/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/user/.virtualenvs/project/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/.virtualenvs/project/lib/python3.8/site-packages/django_slack_oauth/models.py", line 7, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/home/user/.virtualenvs/project/lib/python3.8/site-packages/django/utils/encoding.py)
```

### PR DESCRIPTION
**Pull request by skorokithakis**

### CODE REVIEW

**Comment by izdi** [comment]
Thank you @skorokithakis

**Comment by skorokithakis** [comment]
No problem! Can you cut a release?

**Comment by izdi** [comment]
Would be a tag from the repo work for you? Having a hard time uploading it to PyPI.

**Comment by skorokithakis** [comment]
Hmm, I'm not sure, depends on how much poetry likes that, but if a tag works, so will a commit. What's the trouble with PyPI?

**Comment by izdi** [comment]
Not sure why Travis fails with 400 bad request. Should probably move to actions
https://travis-ci.org/github/izdi/django-slack-oauth/builds/709545762

image

**Comment by skorokithakis** [comment]
Looks like your description couldn't render, at least that's what the error says.

**Pull request merged**
